services:
  redis:
    image: redis:7.2
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} 
      --maxmemory ${REDIS_MAXMEMORY} 
      --maxmemory-policy ${REDIS_MAXMEMORY_POLICY}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped